#!/usr/bin/env python3
"""
audit/regenerate_table1.py
==========================
Read `output/hcug_results.csv` and emit the LaTeX `tabular` body that should
replace lines 384-405 of `paper/frl_paper.tex`.

The harness recommends running this any time `output/hcug_results.csv` changes
(i.e., any time the pipeline re-runs).

Output goes to stdout AND to `audit/_regenerated_table1.tex`.  The latter
file is gitignored; it is a staging artifact.  To apply the change to the
paper:

    1. Run `python audit/regenerate_table1.py`.
    2. Open `audit/_regenerated_table1.tex` and copy the lines.
    3. Replace the corresponding lines in `paper/frl_paper.tex`.
    4. Re-run `bash audit/run.sh` to confirm the audit goes GREEN for Table 1.

Issuer column mapping comes from `data/fund_metadata.csv`.
"""
from __future__ import annotations

import math
import sys
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parent.parent
HCUG = REPO / "output" / "hcug_results.csv"
META = REPO / "data" / "fund_metadata.csv"
OUT  = REPO / "audit" / "_regenerated_table1.tex"

# Order in the original Table 1 (paper line 385-404).  SPY last.
ORDER = ["IEF", "TLT", "AGG", "LQD", "MUB", "EMB", "HYG",
         "BND", "VCIT", "VTEB",
         "GOVT", "SPIB",
         "XBB", "ZAG", "VAB",
         "IUSU", "AGGH", "IBGS", "IS04",
         "SPY"]


def p_band(p_perm: float, q_FDR: float | None) -> str:
    """LaTeX-formatted p-value band, matching paper convention."""
    if p_perm is None or (isinstance(p_perm, float) and math.isnan(p_perm)):
        return r"\multicolumn{1}{c}{n/a}"
    if p_perm < 0.001:
        return r"$<\!0.001$"
    if p_perm < 0.01:
        return f"{p_perm:.3f}"
    return f"{p_perm:.3f}"


def q_band(q: float | None) -> str:
    if q is None or (isinstance(q, float) and math.isnan(q)):
        return r"\multicolumn{1}{c}{--}"
    if q < 0.001:
        return r"$<\!0.001$"
    return f"{q:.3f}"


def sig_marker(q: float | None) -> str:
    if q is None or (isinstance(q, float) and math.isnan(q)):
        return r"n.s."
    if q < 0.001:
        return r"***"
    if q < 0.01:
        return r"**"
    if q < 0.05:
        return r"*"
    return r"n.s."


def main() -> int:
    if not HCUG.exists():
        sys.exit(f"missing {HCUG} — run code/04_hcug_test.py first")
    if not META.exists():
        sys.exit(f"missing {META}")
    hcug = pd.read_csv(HCUG)
    meta = pd.read_csv(META)
    df = hcug.merge(meta[["ticker", "issuer"]], on="ticker", how="left")

    lines = []
    lines.append(r"% AUTO-GENERATED by audit/regenerate_table1.py from output/hcug_results.csv")
    lines.append(r"% Replace lines 384-405 of frl_paper.tex with this body.")
    lines.append(r"\begin{tabular}{lcrrrrrcc}")
    lines.append(r"\toprule")
    lines.append(r"Ticker & Issuer & $N_w$ & Fri \% & $G$ & $p_{\mathrm{perm}}$ & "
                  r"$q_{\mathrm{FDR}}$ & Sig. & Friday flag \\")
    lines.append(r"\midrule")
    for t in ORDER:
        row = df.loc[df["ticker"] == t]
        if len(row) == 0:
            continue
        r = row.iloc[0]
        issuer = r["issuer"] if pd.notna(r["issuer"]) else ""
        issuer = {"State Street": "State Street", "Canadian": "Canadian",
                  "UCITS": "UCITS", "iShares": "iShares", "Vanguard": "Vanguard",
                  "SSGA": "SSGA"}.get(issuer, issuer)
        n_w = int(r["N_weeks"])
        fri = float(r["fri_pct"])
        G   = float(r["G_stat"])
        sig = sig_marker(r["q_FDR"])
        flag = "Yes" if (pd.notna(r["q_FDR"]) and r["q_FDR"] < 0.05) else "No"
        lines.append(
            f"{t:5s} & {issuer:12s} & {n_w:>4d} & {fri:5.1f} & {G:5.1f} & "
            f"{p_band(r['p_perm'], r['q_FDR']):>9s} & {q_band(r['q_FDR']):>9s} & "
            f"{sig:5s} & {flag} \\\\"
        )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")

    body = "\n".join(lines)
    print(body)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body, encoding="utf-8")
    print(f"\n[regenerate_table1] also wrote {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
